export const FOLLOW_USER_REQUEST = "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAILURE = "FOLLOW_USER_FAILURE";

export const UNFOLLOW_USER_REQUEST = "UNFOLLOW_USER_REQUEST";
export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_FAILURE = "UNFOLLOW_USER_FAILURE";

export const GET_FOLLOWERS_REQUEST = "GET_FOLLOWERS_REQUEST";
export const GET_FOLLOWERS_SUCCESS = "GET_FOLLOWERS_SUCCESS";
export const GET_FOLLOWERS_FAILURE = "GET_FOLLOWERS_FAILURE";

export const GET_FOLLOWING_REQUEST = "GET_FOLLOWING_REQUEST";
export const GET_FOLLOWING_SUCCESS = "GET_FOLLOWING_SUCCESS";
export const GET_FOLLOWING_FAILURE = "GET_FOLLOWING_FAILURE";


export const IS_FOLLOWING_THIS_REQUEST = "IS_FOLLOWING_THIS_REQUEST";
export const IS_FOLLOWING_THIS_SUCCESS = "IS_FOLLOWING_THIS_SUCCESS";
export const IS_FOLLOWING_THIS_FAILURE = "IS_FOLLOWING_THIS_FAILURE";


export const  CLEAR_FOLLOW_ERROR = "CLEAR_FOLLOW_ERROR";
