// Action types
export const ADD_LIKE_REQUEST = "ADD_LIKE_REQUEST";
export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS";
export const ADD_LIKE_FAILURE = "ADD_LIKE_FAILURE";

export const DELETE_LIKE_REQUEST = "DELETE_LIKE_REQUEST";
export const DELETE_LIKE_SUCCESS = "DELETE_LIKE_SUCCESS";
export const DELETE_LIKE_FAILURE = "DELETE_LIKE_FAILURE";

export const GET_PERSONAL_LIKES_REQUEST = "GET_PERSONAL_LIKES_REQUEST";
export const GET_PERSONAL_LIKES_SUCCESS = "GET_PERSONAL_LIKES_SUCCESS";
export const GET_PERSONAL_LIKES_FAILURE = "GET_PERSONAL_LIKES_FAILURE";

export const CHECK_USER_LIKED_TWEET_REQUEST = 'CHECK_USER_LIKED_TWEET_REQUEST';
export const CHECK_USER_LIKED_TWEET_SUCCESS = 'CHECK_USER_LIKED_TWEET_SUCCESS';
export const CHECK_USER_LIKED_TWEET_FAILURE = 'CHECK_USER_LIKED_TWEET_FAILURE';

export const  CLEAR_LIKE_ERROR = "CLEAR_LIKE_ERROR";