// trendingConstants.js
export const GET_TRENDING_REQUEST = 'GET_TRENDING_REQUEST';
export const GET_TRENDING_SUCCESS = 'GET_TRENDING_SUCCESS';
export const GET_TRENDING_FAILURE = 'GET_TRENDING_FAILURE';

export const GET_TRENDING_BY_CHOICES_REQUEST = 'GET_TRENDING_BY_CHOICES_REQUEST';
export const GET_TRENDING_BY_CHOICES_SUCCESS = 'GET_TRENDING_BY_CHOICES_SUCCESS';
export const GET_TRENDING_BY_CHOICES_FAILURE = 'GET_TRENDING_BY_CHOICES_FAILURE';

export const CLEAR_TRENDING_ERRORS = 'CLEAR_TRENDING_ERRORS'