
// Tweet action types
// Tweet action types
export const CREATE_TWEET_REQUEST = 'CREATE_TWEET_REQUEST';
export const CREATE_TWEET_SUCCESS = 'CREATE_TWEET_SUCCESS';
export const CREATE_TWEET_FAILURE = 'CREATE_TWEET_FAILURE';

export const UPDATE_TWEET_REQUEST = 'UPDATE_TWEET_REQUEST';
export const UPDATE_TWEET_SUCCESS = 'UPDATE_TWEET_SUCCESS';
export const UPDATE_TWEET_FAILURE = 'UPDATE_TWEET_FAILURE';

export const DELETE_TWEET_REQUEST = 'DELETE_TWEET_REQUEST';
export const DELETE_TWEET_SUCCESS = 'DELETE_TWEET_SUCCESS';
export const DELETE_TWEET_FAILURE = 'DELETE_TWEET_FAILURE';

export const FETCH_PERSONAL_TWEETS_REQUEST = 'FETCH_PERSONAL_TWEETS_REQUEST';
export const FETCH_PERSONAL_TWEETS_SUCCESS = 'FETCH_PERSONAL_TWEETS_SUCCESS';
export const FETCH_PERSONAL_TWEETS_FAILURE = 'FETCH_PERSONAL_TWEETS_FAILURE';

export const FETCH_ALL_TWEETS_REQUEST = 'FETCH_ALL_TWEETS_REQUEST';
export const FETCH_ALL_TWEETS_SUCCESS = 'FETCH_ALL_TWEETS_SUCCESS';
export const FETCH_ALL_TWEETS_FAILURE = 'FETCH_ALL_TWEETS_FAILURE';

export const FETCH_OTHER_TWEETS_REQUEST = 'FETCH_OTHER_TWEETS_REQUEST';
export const FETCH_OTHER_TWEETS_SUCCESS = 'FETCH_OTHER_TWEETS_SUCCESS';
export const FETCH_OTHER_TWEETS_FAILURE = 'FETCH_OTHER_TWEETS_FAILURE';


export const CLEAR_TWEET_ERRORS = 'CLEAR_TWEET_ERRORS';

